---
repos:
  ######################################
  # Hooks for all projects
  ######################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types:
          - javascript
          - ts
      - id: check-executables-have-shebangs

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.7.0
    hooks:
      - id: conventional-gitmoji

  - repo: local
    hooks:
      #     - id: no-repeated-whitespace
      #       name: No repeated spaces
      #       entry: '\S+\s{2,}'
      #       language: pygrep
      #       types: [text]
      #       exclude_types: [javascript, ts]
      #
      #     - id: no-bracket-links
      #       name: "Brackets should not be inside links [[link]](url) -> [[link](url)]"
      #       entry: '\]\]\('
      #       language: pygrep
      #       types: [markdown]
      #
      - id: no-http
        name: URLs must use HTTPS
        entry: "http:"
        language: pygrep
        types_or: [markdown, yaml]
        exclude: |
          (?x)^(
              .pre-commit-config.yaml|
              pnpm-lock.yaml
          )$

  ######################################
  # docs and other markdown files
  ######################################
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        files: ".*.md"
        # MD013: line too long
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        args: [--fix, --disable, MD013, MD033, MD041, MD046, MD040, "--"]

  ######################################
  # frontend project
  ######################################
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.37.0
    hooks:
      - id: eslint
        types: [file]
        args: [--fix, --config, app/eslint.config.js]
        files: ^app/.*\.(js|ts|tsx)$
        additional_dependencies:
          - eslint
          - eslint-plugin-react
          - typescript-eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--config, app/.prettierrc, --write] # edit files in-place
        files: ^app/.*
        additional_dependencies:
          - prettier
          - prettier-plugin-react
          - react
